### ISSUE TITLE
Device heatup and shutdown on startup

### ISSUE THREAD

**Issue by kgursu** [yzyhk904/compatible-magisk-mirroring#1]
I have a satsuki (Sony Xperia Z5 Premium) device with a A11 custom ROM, which has surprisingly working Zygisk with Kitsune Magisk. On that device Compatible Magisk Mirroring made the device unusable. I have tried several combinations of disabling modules. I suspect yours might be the culprit. Here are several bootlogs during these experiments:
![bootlog-2024-03-28-18-27-58.tar.gz](https://github.com/yzyhk904/compatible-magisk-mirroring/files/14792323/bootlog-2024-03-28-18-27-58.tar.gz)

![bootlog-2024-03-28-18-39-32.tar.gz](https://github.com/yzyhk904/compatible-magisk-mirroring/files/14792320/bootlog-2024-03-28-18-39-32.tar.gz)

![bootlog-2024-03-28-18-33-51.tar.gz](https://github.com/yzyhk904/compatible-magisk-mirroring/files/14792322/bootlog-2024-03-28-18-33-51.tar.gz)

![bootlog-2024-03-28-18-23-40.tar.gz](https://github.com/yzyhk904/compatible-magisk-mirroring/files/14792321/bootlog-2024-03-28-18-23-40.tar.gz)

**Comment by kgursu** [comment]
I recently saw the new version 1.1.1. I applied it and the issue was resolved.
Sorry and thanks...

**Comment by yzyhk904** [comment]
Version 1.1.1 was uploaded before 5 days. What version did you tried? "Compatible Magisk-mirroring" does nothing but mounting system partitions. I think the cause of the heatup is another.

**Comment by yzyhk904** [comment]
Moved to [Magisk-Modules-Alt-Repo](https://github.com/Magisk-Modules-Alt-Repo/compatible-magisk-mirroring).
